// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/mytheresa/go-hiring-challenge/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCategoryRepository creates a new instance of MockCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryRepository {
	mock := &MockCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategoryRepository is an autogenerated mock type for the CategoryRepository type
type MockCategoryRepository struct {
	mock.Mock
}

type MockCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryRepository) EXPECT() *MockCategoryRepository_Expecter {
	return &MockCategoryRepository_Expecter{mock: &_m.Mock}
}

// CreateCategory provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) CreateCategory(category *models.Category) error {
	ret := _mock.Called(category)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*models.Category) error); ok {
		r0 = returnFunc(category)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategoryRepository_CreateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCategory'
type MockCategoryRepository_CreateCategory_Call struct {
	*mock.Call
}

// CreateCategory is a helper method to define mock.On call
//   - category *models.Category
func (_e *MockCategoryRepository_Expecter) CreateCategory(category interface{}) *MockCategoryRepository_CreateCategory_Call {
	return &MockCategoryRepository_CreateCategory_Call{Call: _e.mock.On("CreateCategory", category)}
}

func (_c *MockCategoryRepository_CreateCategory_Call) Run(run func(category *models.Category)) *MockCategoryRepository_CreateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Category
		if args[0] != nil {
			arg0 = args[0].(*models.Category)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCategoryRepository_CreateCategory_Call) Return(err error) *MockCategoryRepository_CreateCategory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategoryRepository_CreateCategory_Call) RunAndReturn(run func(category *models.Category) error) *MockCategoryRepository_CreateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllCategories provides a mock function for the type MockCategoryRepository
func (_mock *MockCategoryRepository) GetAllCategories() ([]models.Category, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllCategories")
	}

	var r0 []models.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.Category, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.Category); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryRepository_GetAllCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCategories'
type MockCategoryRepository_GetAllCategories_Call struct {
	*mock.Call
}

// GetAllCategories is a helper method to define mock.On call
func (_e *MockCategoryRepository_Expecter) GetAllCategories() *MockCategoryRepository_GetAllCategories_Call {
	return &MockCategoryRepository_GetAllCategories_Call{Call: _e.mock.On("GetAllCategories")}
}

func (_c *MockCategoryRepository_GetAllCategories_Call) Run(run func()) *MockCategoryRepository_GetAllCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCategoryRepository_GetAllCategories_Call) Return(categorys []models.Category, err error) *MockCategoryRepository_GetAllCategories_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *MockCategoryRepository_GetAllCategories_Call) RunAndReturn(run func() ([]models.Category, error)) *MockCategoryRepository_GetAllCategories_Call {
	_c.Call.Return(run)
	return _c
}
