// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/mytheresa/go-hiring-challenge/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// GetProductByCode provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) GetProductByCode(code string) (*models.Product, error) {
	ret := _mock.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByCode")
	}

	var r0 *models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.Product, error)); ok {
		return returnFunc(code)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.Product); ok {
		r0 = returnFunc(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_GetProductByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByCode'
type MockProductRepository_GetProductByCode_Call struct {
	*mock.Call
}

// GetProductByCode is a helper method to define mock.On call
//   - code string
func (_e *MockProductRepository_Expecter) GetProductByCode(code interface{}) *MockProductRepository_GetProductByCode_Call {
	return &MockProductRepository_GetProductByCode_Call{Call: _e.mock.On("GetProductByCode", code)}
}

func (_c *MockProductRepository_GetProductByCode_Call) Run(run func(code string)) *MockProductRepository_GetProductByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProductRepository_GetProductByCode_Call) Return(product *models.Product, err error) *MockProductRepository_GetProductByCode_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProductRepository_GetProductByCode_Call) RunAndReturn(run func(code string) (*models.Product, error)) *MockProductRepository_GetProductByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetProducts provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) GetProducts(filter models.ProductFilter) ([]models.Product, int64, error) {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetProducts")
	}

	var r0 []models.Product
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(models.ProductFilter) ([]models.Product, int64, error)); ok {
		return returnFunc(filter)
	}
	if returnFunc, ok := ret.Get(0).(func(models.ProductFilter) []models.Product); ok {
		r0 = returnFunc(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(models.ProductFilter) int64); ok {
		r1 = returnFunc(filter)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(models.ProductFilter) error); ok {
		r2 = returnFunc(filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProductRepository_GetProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProducts'
type MockProductRepository_GetProducts_Call struct {
	*mock.Call
}

// GetProducts is a helper method to define mock.On call
//   - filter models.ProductFilter
func (_e *MockProductRepository_Expecter) GetProducts(filter interface{}) *MockProductRepository_GetProducts_Call {
	return &MockProductRepository_GetProducts_Call{Call: _e.mock.On("GetProducts", filter)}
}

func (_c *MockProductRepository_GetProducts_Call) Run(run func(filter models.ProductFilter)) *MockProductRepository_GetProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.ProductFilter
		if args[0] != nil {
			arg0 = args[0].(models.ProductFilter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProductRepository_GetProducts_Call) Return(products []models.Product, n int64, err error) *MockProductRepository_GetProducts_Call {
	_c.Call.Return(products, n, err)
	return _c
}

func (_c *MockProductRepository_GetProducts_Call) RunAndReturn(run func(filter models.ProductFilter) ([]models.Product, int64, error)) *MockProductRepository_GetProducts_Call {
	_c.Call.Return(run)
	return _c
}
